# Generated by Django 5.1.7 on 2025-04-10 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='id_Categorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.categorie'),
        ),
        migrations.AlterField(
            model_name='article',
            name='images',
            field=models.ImageField(upload_to=''),
        ),
    ]
