# Generated by Django 5.1.7 on 2025-05-10 01:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_quiz_video_flashcard'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flashcard',
            old_name='contenu',
            new_name='answer',
        ),
        migrations.RemoveField(
            model_name='flashcard',
            name='auteur',
        ),
        migrations.RemoveField(
            model_name='flashcard',
            name='titre',
        ),
        migrations.AddField(
            model_name='flashcard',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.categorie'),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='question',
            field=models.TextField(default='Question par défaut'),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='flashcards/videos/'),
        ),
    ]
